audit_header: false
title: Sacramento's Best Real Estate Training
description: >-
  Tom Daves, a top Real Estate Agent in Sacramento, shares his own internal real
  estate agent training for free. His Real Estate Training, Tips and Advice will
  help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Join Our Team
    url: /join-our-team/
  - title: Events
    url:
  - title: Free Strategy Call
    url: /contact/
client:
  name: Tom Daves
  title:
  license_number:
  about_markdown: >-
    eXp Realty - Tom Daves is comprised of a team of local real estate
    professionals committed to selling some of the most desired homes in Greater
    Sacramento Area. Selling these "right addresses" is the mission of eXp
    Realty - Tom Daves. Let us know what you're looking for. Please take
    advantage of the helpful tools on this website, including our exclusive
    Greater Sacramento Area Real Estate search, but also feel free to contact us
    personally.
  market: Sacramento
  brand: Tom Daves Team
  brokerage:
  address: '1478 Stone Point Suite 450<br>Roseville, CA 95661'
  phone: 916-296-5841
  phone_type:
  phone2:
  phone2_type:
  email: tom@tomdavesteam.com
  url: 'https://tdaves.com/'
sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: Looking to Build Your Real Estate Career?
    CTA_text: Let's talk about how Tom Daves Team can take your business to new heights.
    CTA_link_text: Free Strategy Session
    CTA_url: /contact/
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: 'http://fillmurray.com/200/200'
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: 'http://eyegoop.com'
socials:
  review_sm_icons: false
  facebook_url:
  linkedin_url:
  gplus_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:
podcast:
  title: Sacramento Real Estate Podcast with Tom Daves
  categories:
    - Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the Sacramento
    Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from Tom Daves Team - your professional
    Sacramento Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in Sacramento, home
    selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: Tom Daves
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Sacramento Real Estate Video Blog
  hero_background_hex: '#999999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#f5821f'
  theme_color: '#17244c'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
navbar_colors:
  border_bottom:
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: 'rgba(0, 0, 0, 0)'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: 'rgba(0, 0, 0, 0)'
  button_text_color: '#f5821f'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'